/**
 * Your words. Everything in this file is shown exactly as written and is never
 * sent to or generated by any model. Edit freely — add letters, swap the
 * moments for real ones, change the signature.
 */

export interface Letter {
  /** 2–4 sentences. Line breaks are respected. */
  body: string;
  /** Shown under the letter, right-aligned. */
  sign?: string;
}

export interface Moment {
  /** Any short label — a date, a season, a place. */
  when: string;
  /** One evocative line about it. */
  line: string;
}

export const LETTERS: Letter[] = [
  {
    body:
      "I keep noticing small things and wanting to tell you about them. A good sky, a song that sounds like you, a sentence I liked. You've become the person I explain the world to.\n\nThat's all this is. A place to keep some of it.",
    sign: "— me",
  },
  {
    body:
      "On the days I'm quiet, it isn't distance. It's that being near you is the one place I don't have to perform anything. You make stillness feel like company.",
    sign: "— yours",
  },
  {
    body:
      "I used to think the big feelings would announce themselves. Turns out it was the ordinary evenings — you on the couch, half-asleep, telling me about your day — that did it.",
    sign: "— me",
  },
  {
    body:
      "If you're reading this on a hard day: I'm not going anywhere. Pick the flower, open a sweet, let the bear be soft at you. I built all of it thinking about your face.",
    sign: "— always",
  },
  {
    body:
      "I don't need every lifetime to look the same. I just need you in the room when I turn around. So far, so good.",
    sign: "— yours, still",
  },
];

// Replace these with real ones whenever you like — a date and a single line.
export const MOMENTS: Moment[] = [
  { when: "the first walk", line: "we ran out of street before we ran out of things to say" },
  { when: "that rainy week", line: "you fell asleep mid-sentence and I stayed up smiling" },
  { when: "the small kitchen", line: "burnt the first thing we cooked, kept the recipe anyway" },
  { when: "a grey morning", line: "you said my name like it was good news" },
  { when: "now", line: "still choosing you — today, and the next one" },
];
